In [4]:
class array:
    def __init__(self,lst):
        self.lst = lst
    def __str__(self):
        st = str(self.lst).replace(',', '')
        return st
    def __add__(self,other):
        adder = []
        if len(self.lst)==len(other.lst):
            for i in range(len(self.lst)):
                adder.append(self.lst[i]+other.lst[i])
            return array(adder)
        else:
            return 'Length of the arrays are not equal!'
    def reshape(self, m, n):
        M = []
        tmp = []
        for i in self.lst:
            tmp.append(i)
            if len(tmp) == n:
                M.append(tmp)
                tmp = []
        return array(M)

arr1 = array([2,4,6,8,1,52])
arr2 = array([4,5,6,8,9,2])
out = arr1.reshape(2,3)
# out = arr1+arr2
# print(out, type(out))
print(out)


[6 9 12 16 10 54] <class '__main__.array'>
[6 9 12 16 10 54]


In [2]:
import numpy as np
ls = [1,200,3,4,5,6]
arr = np.array(ls)
# print(f'{arr=}')
# print(f'{ls=}')
print(arr, type(arr))
print(ls)
print(isinstance(ls, np.ndarray))

[  1 200   3   4   5   6] <class 'numpy.ndarray'>
[1, 200, 3, 4, 5, 6]
False


In [11]:
import numpy as np
import time
data  = range(100000)
arr1 = np.array(data)
lst1 = list(data)

In [3]:
arr1 = np.array([10,4,6])
arr2 = np.array([8,6,3])
print(arr1+arr2)

[18 10  9]


In [55]:
start = time.time()
list_data = [i*2 for i in lst1]
stop  = time.time()
print('list Time', stop-start)

start = time.time()
arr_data = arr1*2
stop  = time.time()
print('arr Time', stop-start)

list Time 0.009553670883178711
arr Time 0.0025298595428466797
