In [41]:
#Welcome to code with harry program
#conversion from other python structure
import numpy as np
listarray = np.array([[2,3,4],[4,5,6],[7,8,9]])

In [42]:
listarray

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(listarray.shape)
print(listarray.size)
print(listarray.dtype)

(3, 3)
9
int32


In [44]:
rng = np.arange(3)
print(rng)

[0 1 2]


In [45]:
x = [[4,2,3],[4,5,6],[7,1,0]]
arr = np.array(x)


In [46]:
arr

array([[4, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
np.sqrt(arr)

array([[2.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [57]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

# count_nonzero

In [59]:
np.count_nonzero(arr)

8

In [60]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [48]:
print(arr.sum(axis = 1))
print(arr.sum(axis = 0))


[ 9 15  8]
[15  8  9]


In [49]:
print(arr.argmax(axis = 0))
print(arr.argmax(axis = 1))

[2 1 1]
[0 2 0]


In [50]:
arr.ravel()

array([4, 2, 3, 4, 5, 6, 7, 1, 0])

In [51]:
arr.reshape(9,1)

array([[4],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [52]:
#Transpose
print(arr.T)
print()
print(arr.ndim)

[[4 4 7]
 [2 5 1]
 [3 6 0]]

2


In [53]:
arr.nbytes

36

In [54]:
one_dim_arr = np.array([1,2,34,54,23,423])

In [55]:
# To get the index of maximum and minimum element
print(one_dim_arr.argmax())
print(one_dim_arr.argmin())

5
0


In [56]:
# To sort the index of numpy array
print(one_dim_arr.argsort())

[0 1 4 2 3 5]


In [61]:
import sys

In [63]:
py_ar = [0,4,55,2]


In [64]:
np_ar = np.array(py_ar)

In [65]:
sys.getsizeof(1) * len(py_ar)

112

In [66]:
np_ar.itemsize* np_ar.size

16