In [21]:
import numpy as np

In [5]:
#example 1
lst = [2,3,4,5,6]
arr = np.array(lst)
print(arr, arr.ndim)

[2 3 4 5 6] 1


In [12]:
lst = [[2,3,6,4],[6,4,7,8]]
arr = np.array(lst)
print(arr)
print(arr.shape)
print(arr.ndim)

[[2 3 6 4]
 [6 4 7 8]]
(2, 4)
2


In [15]:
arr1= np.array([3,4,5,6,8,3])
arr2 = np.array([2,3,4,5,6,6])

# arr1.shape = (3,2)
m1 = arr1.reshape(2,3)
m2 = arr2.reshape(2,3)
n = np.add(m1,m2)
print(n)

# print(m2)

[[ 5  7  9]
 [11 14  9]]


In [16]:
#To make the elements to the list according to the shape
import numpy as np
lst = list(map(int, input().split()))
arr = np.array(lst).reshape(3,3)
print(arr)


[[4 5 6]
 [8 9 8]
 [5 6 4]]


In [20]:
import numpy as np
r,c = list(map(int, input().split()))
out = np.eye(r,c)
print(out)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#task 4
import numpy as np
arr1 = list(map(int, input().split()))
arr2 = list(map(int, input().split()))
r, c = list(map(int, input().split()))
print('array1:', arr1)
print('array2:', arr2)
m1= np.array(arr1).reshape(r, c)
m2= np.array(arr2).reshape(r, c)
addition = np.add(m1, m2)
substration = np.subtract(m1, m2)
multip = np.multiply(m1, m2)
div = np.floor_divide(m1, m2)
mod= np.mod(m1, m2)
power = np.power(m1,m2)
print(addition)
print(substration)
print(multip)
print(div)
print(mod)
print(power)


array1: [5, 6, 8, 9]
array2: [5, 6, 8, 9]
[[10 12]
 [16 18]]
[[0 0]
 [0 0]]
[[25 36]
 [64 81]]
[[1. 1.]
 [1. 1.]]
[[0 0]
 [0 0]]
[[     3125     46656]
 [ 16777216 387420489]]


In [6]:
#transpose
import numpy as np
arr1 = list(map(int, input().split()))
r, c = list(map(int, input().split()))
print('array1:', arr1)
m1= np.array(arr1).reshape(r, c)
tran = np.transpose(m1)
print(tran)

array1: [5, 6, 9, 8, 6, 8, 9, 5, 8]
[[5 8 9]
 [6 6 5]
 [9 8 8]]


In [ ]:
import numpy as np
arr1 = list(map(int, input().split()))
r, c = list(map(int, input().split()))
print('array1:', arr1)
m1= np.array(arr1).reshape(r, c)
flat = np.flatten(m1)
print(tran)