In [5]:
import numpy as np

In [7]:
ls = [128,6,130]
data = np.array(ls, dtype = 'int8')
print(data)

[-128    6 -126]


C:\Users\ASUS1\AppData\Local\Temp\ipykernel_8060\2982428514.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  data = np.array(ls, dtype = 'int8')
C:\Users\ASUS1\AppData\Local\Temp\ipykernel_8060\2982428514.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 130 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  data = np.array(ls, dtype = 'int8')


In [8]:
ls = [-1,6,-2]
data = np.array(ls, dtype = 'int8')
print(data)

[-1  6 -2]


In [14]:
ls = [127,6,256]
data = np.array(ls, dtype = 'int8')
print(data)

[127   6   0]


C:\Users\ASUS1\AppData\Local\Temp\ipykernel_8060\3967718496.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  data = np.array(ls, dtype = 'int8')
